### ISSUE TITLE
This plugin doesn't remove CSS IDs anymore, but there's a fix

### ISSUE THREAD

**Issue by ponchohoncho** [primozcigler/remove-css-ids#1]
Hello,

I'm using this plugin to facilitate mod_pagespeed, but it doesn't strip the CSS IDs like it says it does. I found a replacement function here: https://blog.codecentric.de/en/2011/10/wordpress-and-mod_pagespeed-why-combine_css-does-not-work/

line 19 just needs to be replaced with this:
`return preg_replace("/id='.*-css'/", "", $link);`

I hope this helps.

**Comment by primozcigler** [comment]
Hi,

Thanks for reporting this. I am not maintaining the plugin anymore because Google has dropped support for mod_pagespeed as well. However, if you submit a PR I'll be more than happy to merge it here for you.

Is that OK?
